# languages.py

LANGUAGES = {
    "Русский (Russian)": {
        "check_disk_space": "Проверять остаток памяти при запуске",
        "check_disk_space_help": "Программа предупредит, если на системном диске осталось менее 2ГБ",
        "low_disk_space_title": "Мало места на диске",
        "low_disk_space_message": "На системном диске C:\\ осталось мало памяти. Для записи длинных аудио без ошибок рекомендуем иметь не менее 2ГБ памяти на системном диске.",
        "reset_settings": "Сброс настроек по умолчанию",
        "reset_settings_confirm": "Вы уверены что хотите сбросить все настройки к значениям по умолчанию?",
        "reset_settings_success": "Настройки успешно сброшены!",
        "device_setting_label": "Устройство для записи",
        "device_help": "Как говорится: «Если работает — не трогай»",
        "exit_unsaved_warning": "На данный момент ведется запись и/или аудио не было сохранено.\n Вы точно хотите выйти?",
        "save_path_label": "Папка для сохранения записей",
        "tray_settings": "Настройки",
        "lang_help": "Могу даже на китайском!",
        "no_file": "Выберите файл",
        "work_background_help": "Позволяет записывать аудио и прослушивать записи когда приложение свернуто",
        "autostart_help": "Чтобы всегда быть под рукой",
        "auto_save_help": "Запись сохранится сразу на диск без предварительного прослушивания в плеере",
        "always_on_top_help": "Приложение будет закреплено поверх всех остальных окон в системе",
        "hotkeys_label": "Горячие клавиши",
        "hotkeys_help": "[Ctrl+Space] Старт/Стоп, [Ctrl+Shift+Space] Пауза, [Ctrl+Shift+S] Сохранить",
        "exit_title": "Выход",
        "exit_confirm": "Вы точно хотите выйти?",
        "dont_ask": "Не спрашивать больше",
        "exit_btn": "Выход",
        "cancel_btn": "Отмена",
        "always_on_top": "Поверх всех окон",
        "auto_save": "Автоматическое сохранение на диск",
        "nav_rec": "ДИКТОФОН",
        "nav_set": "НАСТРОЙКИ",
        "nav_settings": "ПАРАМЕТРЫ ЗАПИСИ",
        "nav_about": "О ПРОГРАММЕ",
        "status_ready": "ГОТОВ К ЗАПИСИ",
        "status_recording": "ИДЕТ ЗАПИСЬ",
        "status_paused": "ЗАПИСЬ ПРИОСТАНОВЛЕНА",
        "btn_record": "ЗАПИСЬ",
        "btn_stop": "СТОП",
        "btn_pause": "ПАУЗА",
        "btn_resume": "ПРОДОЛЖИТЬ",
        "input_volume": "ГРОМКОСТЬ ВХОДА",
        "device": "Устройство",
        "format": "Формат",
        "noise": "Шумоподавление",
        "now_playing": "Воспроизводится",
        "tab_settings": "ПАРАМЕТРЫ ПРИЛОЖЕНИЯ",
        "work_background": "Работать в фоне",
        "language_label": "Язык (Language)",
        "folder_label": "Папка",
        "bitrate": "Битрейт",
        "frequency": "Частота",
        "mode": "Режим записи",
        "temp_rec_name": "Текущая запись (не сохранено)",
        "status_done": "ЗАПИСЬ ГОТОВА",
        "status_deleted": "ЗАПИСЬ УДАЛЕНА",
        "btn_delete": "УДАЛИТЬ",
        "warn_save": "Сначала сохраните или удалите текущую запись",
        "player_title": "ПЛЕЕР",
        "play_volume": "Громкость",
        "btn_save": "СОХРАНИТЬ",
        "list_date": "ДАТА",
        "list_name": "ИМЯ ФАЙЛА",
        "list_current": "🔴 ТЕКУЩАЯ ЗАПИСЬ",
        "library_title": "ПОСЛЕДНИЕ ЗАПИСИ",
        "btn_choose_folder": "Выбрать папку",
        "btn_open_explorer": "Открыть папку",
        "tray_open": "Открыть",
        "tray_exit": "Выход",
        "autostart": "Запускаться вместе с Windows",
        "status_save_success": "ФАЙЛ СОХРАНЕН",
        "status_save_error": "ОШИБКА СОХРАНЕНИЯ",
        "saving_title": "Сохранение",
        "saving_message": "Сохранение аудио файла...\nПожалуйста, подождите...",
        "btn_cancel": "ОТМЕНА",
        "unit_sec": "сек",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Версия 0.6 Beta, возможны баги",
        "about_description": (
            "Ваш звук под полным контролем. JB Audio Recorder — это легкий и мощный инструмент для тех, кому важно качество. "
            "Забудьте о сложных настройках: записывайте аудио в популярных форматах с выбором битрейта и частоты. "
            "Встроенный алгоритм интеллектуального шумоподавления очистит голос от фоновых звуков.\n\n"
            "Удобный плеер и библиотека. Больше не нужно искать файлы по всей системе. Прямо в приложении прослушайте запись "
            "и решите — сохранить её или перезаписать. Все удачные записи попадают в наглядную библиотеку, "
            "где их легко найти и открыть одним кликом.\n\n"
            "Работайте так, как вам удобно. Диктофон может работать в фоновом режиме или быть всегда под рукой «поверх всех окон». "
            "Управляйте записью горячими клавишами и не переживайте за результат — система предупредит о несохраненном файле при выходе."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "English": {
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "check_disk_space": "Check disk space",
        "check_disk_space_help": "Warning if less than 2GB free",
        "low_disk_space_title": "Low Disk Space",
        "low_disk_space_message": "Low disk space. At least 2GB recommended for long recordings.",
        "reset_settings": "Reset to default settings",
        "reset_settings_confirm": "Are you sure you want to reset all settings to default values?",
        "reset_settings_success": "Settings successfully reset!",
        "device_setting_label": "Recording Device",
        "device_help": "As they say: 'If it works, don't touch it'",
        "exit_unsaved_warning": "Recording is in progress and/or audio hasn't been saved yet.\nAre you sure you want to exit?",
        "save_path_label": "Folder for saving recordings",
        "tray_settings": "Settings",
        "lang_help": "I can even speak Chinese!",
        "choose_file": "Choose file",
        "no_file": "No file",
        "work_background_help": "Allows recording and playback while the app is minimized",
        "autostart_help": "Always available at your fingertips",
        "auto_save_help": "Recording is saved directly to disk without preview in the player",
        "always_on_top_help": "The app will stay on top of all other windows",
        "hotkeys_label": "Hotkeys",
        "hotkeys_help": "[Ctrl+Space] Rec/Stop, [Ctrl+Shift+Space] Pause, [Ctrl+Shift+S] Save",
        "exit_title": "Exit",
        "exit_confirm": "Are you sure you want to exit?",
        "dont_ask": "Don't ask again",
        "exit_btn": "Exit",
        "cancel_btn": "Cancel",
        "always_on_top": "Always on top",
        "auto_save": "Automatic saving to disk",
        "nav_rec": "RECORDER",
        "nav_set": "SETTINGS",
        "nav_settings": "RECORDING PARAMETERS",
        "nav_about": "ABOUT",
        "status_ready": "READY TO RECORD",
        "status_recording": "RECORDING IN PROGRESS",
        "status_paused": "RECORDING PAUSED",
        "btn_record": "RECORD",
        "btn_stop": "STOP",
        "btn_pause": "PAUSE",
        "btn_resume": "RESUME",
        "input_volume": "INPUT VOLUME",
        "device": "Device",
        "format": "Format",
        "noise": "Noise Reduction",
        "now_playing": "Now playing",
        "tab_settings": "APP SETTINGS",
        "work_background": "Work in background",
        "language_label": "Language",
        "folder_label": "Folder",
        "bitrate": "Bitrate",
        "frequency": "Frequency",
        "mode": "Recording Mode",
        "temp_rec_name": "Current recording",
        "status_done": "RECORDING READY",
        "status_deleted": "DELETED",
        "btn_delete": "DELETE",
        "warn_save": "Save or delete recording first!",
        "player_title": "PLAYER",
        "play_volume": "Volume",
        "btn_save": "SAVE",
        "list_date": "DATE",
        "list_name": "FILE NAME",
        "list_current": "🔴 CURRENT RECORDING",
        "library_title": "RECENT RECORDINGS",
        "btn_choose_folder": "Choose folder",
        "btn_open_explorer": "Open Explorer",
        "tray_open": "Open",
        "tray_exit": "Exit",
        "autostart": "Start with Windows",
        "status_save_success": "FILE SAVED",
        "status_save_error": "SAVE ERROR",
        "saving_title": "Saving",
        "saving_message": "Saving audio file...\nPlease wait...",
        "btn_cancel": "CANCEL",
        "unit_sec": "sec",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Version 0.6 Beta, possible bugs",
        "about_description": (
            "Your sound under full control. JB Audio Recorder is a lightweight and powerful tool for those who value quality. "
            "Forget complex settings: record audio in popular formats with selectable bitrate and frequency. "
            "The built-in intelligent noise reduction algorithm cleans your voice from background noise.\n\n"
            "Convenient player and library. No need to search for files across the system. Listen to the recording "
            "right in the app and decide whether to save or overwrite it. All successful recordings go into a visual library, "
            "where they are easy to find and open with one click.\n\n"
            "Work as you like. The recorder fits perfectly into your workflow: it works in the background or stays 'always on top'. "
            "Control recording with hotkeys and rest assured — the system will warn you about unsaved files upon exit."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Дореволюціонный (Prerevolutionary)": {
        "reset_settings": "Сбросить къ настройкамъ по умолчанию",
        "reset_settings_confirm": "Вы уверены что хотите сбросить все настройки к значениям по умолчанию?",
        "reset_settings_success": "Настройки успешно сброшены!",
        "device_setting_label": "Аппаратъ для записи",
        "device_help": "Какъ говорится: «Ежели работаетъ — не трогай»",
        "exit_unsaved_warning": "На данный момент ведется запись и/или аудио не было спасено.\nВы точно хотите выйти?",
        "save_path_label": "Папка для спасенія записей",
        "tray_settings": "Настройки",
        "lang_help": "Сіе уразумѣютъ даже французскіе буржуи!",
        "no_file": "Изберите файлъ",
        "work_background_help": "Дозволяетъ вершить запись и слушать звукъ незамѣтно когда приложеніе свернуто",
        "autostart_help": "Дабы вѣчно быть подъ рукою",
        "auto_save_help": "Запись сохранится немедля на дискъ безъ предварительнаго слушанія въ ґраммофонѣ",
        "always_on_top_help": "Приложеніе будетъ закрѣплено надъ всѣми прочими окнами системы",
        "hotkeys_label": "Горячія клавиши",
        "hotkeys_help": "[Ctrl+Space] Стартъ/Стопъ, [Ctrl+Shift+Space] Пауза, [Ctrl+Shift+S] Сохранить",
        "exit_title": "Выходъ",
        "exit_confirm": "Точно ли изволите выйти?",
        "dont_ask": "Болѣе не вопрошать",
        "exit_btn": "Выходъ",
        "cancel_btn": "Отмѣна",
        "always_on_top": "Надъ всѣми окнами",
        "auto_save": "Автоматическое сохраненіе на пластинку",
        "nav_rec": "ДИКТОФОНЪ",
        "nav_set": "НАСТРОЙКИ",
        "nav_settings": "ПАРАМЕТРЫ ЗАПИСИ",
        "nav_about": "О ПРОГРАММѢ",
        "status_ready": "ГОТОВЪ КЪ ЗАПИСИ",
        "status_recording": "ИДЕТЪ ЗАПИСЬ",
        "status_paused": "ЗАПИСЬ ПРИОСТАНОВЛЕНА",
        "btn_record": "ЗАПИСЬ",
        "btn_stop": "СТОПЪ",
        "btn_pause": "ПАУЗА",
        "btn_resume": "ПРОДОЛЖИТЬ",
        "input_volume": "ГРОМКОСТЬ ВХОДА",
        "device": "Устройство",
        "format": "Форматъ",
        "noise": "Шумоподавленіе",
        "now_playing": "Воспроизводится",
        "tab_settings": "ПАРАМЕТРЫ ПРИЛОЖЕНІЯ",
        "work_background": "Работать въ фонѣ",
        "language_label": "Языкъ (Language)",
        "folder_label": "Папка",
        "bitrate": "Битрейтъ",
        "frequency": "Частота",
        "mode": "Режимъ записи",
        "temp_rec_name": "Текущая запись (не сохранено)",
        "status_done": "ЗАПИСЬ ГОТОВА",
        "status_deleted": "ЗАПИСЬ УДАЛЕНА",
        "btn_delete": "УДАЛИТЬ",
        "warn_save": "Сперва спасите или сотрите текущую запись!",
        "player_title": "ҐРАММОФОНЪ",
        "play_volume": "Громкость",
        "btn_save": "СПАСТИ",
        "list_date": "ДАТА",
        "list_name": "ИМЯ ФАЙЛА",
        "list_current": "🔴 ТЕКУЩАЯ ЗАПИСЬ",
        "library_title": "ПОСЛѢДНИЯ АУДИОЗАПИСИ",
        "btn_choose_folder": "Избрать папку",
        "btn_open_explorer": "Открыть папку",
        "tray_open": "Открыть",
        "tray_exit": "Выходъ",
        "autostart": "Запускаться вмѣстѣ съ Windows",
        "status_save_success": "ФАЙЛЪ СПАСЕНЪ!",
        "status_save_error": "ОШИБКА СПАСЕНІЯ!",
        "btn_cancel": "ОТМѢНА",
        "unit_sec": "сек",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Версія 0.6 Beta, вѣроятно (точнѣе — точно) содержитъ ошибки",
        "about_description": (
            "Профессіональное качество въ одинъ кликъ. JB Audio Recorder — сіе легкій диктофонъ съ мощными возможностями. "
            "Записывайте звукъ въ высокомъ качествѣ, избирая нужный битрейтъ и форматъ. Встроенная система умнаго шумоподавленія "
            "мгновенно очиститъ вашъ глас отъ лишнихъ звуковъ, обезпечивая чистую и четкую запись даже въ шумномъ помѣщеніи.\n\n"
            "Удобство работы и храненія. Слушайте записи тотчас послѣ завершенія во встроенномъ плеерѣ и рѣшайте — спасти ихъ на дискъ или истребить. "
            "Всѣ файлы автоматически организуются въ удобную библіотеку съ поискомъ по датѣ, дабы вы могли мгновенно найти нужный фрагментъ и открыть его.\n\n"
            "Полная интеграція въ вашъ процессъ. Работайте такъ, какъ вамъ удобно: въ фоновомъ режимѣ, поверхъ другихъ оконъ или чрезъ быстрыя горячія клавиши. "
            "Программа всегда упредитъ о неспасеномъ аудіо при выходѣ, гарантируя, что ни одна важная мысль не будетъ потеряна."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "Изъ Россіи съ любовію"
    },
    "Türkçe (Turkish)": {
        "reset_settings": "Varsayılan ayarlara sıfırla",
        "reset_settings_confirm": "Tüm ayarları varsayılan değerlere sıfırlamak istediğinize emin misiniz?",
        "reset_settings_success": "Ayarlar başarıyla sıfırlandı!",
        "device_setting_label": "Kayıt Cihazı",
        "device_help": "Dedikleri gibi: «Çalışıyorsa dokunma»",
        "exit_unsaved_warning": "Şu anda kayıt yapılıyor ve/veya ses kaydedilmedi.\nÇıkmak istediğinize emin misiniz?",
        "save_path_label": "Kayıtların kaydedileceği klasör",
        "tray_settings": "Ayarlar",
        "lang_help": "Çince bile konuşabilirim!",
        "choose_file": "Dosya seç",
        "no_file": "Dosya yok",
        "work_background_help": "Uygulama simge durumuna küçültüldüğünde kayıt ve oynatmaya izin verir",
        "autostart_help": "Her zaman elinizin altında",
        "auto_save_help": "Kayıt, oynatıcıda önizleme yapılmadan doğrudan diske kaydedilir",
        "always_on_top_help": "Uygulama, sistemdeki diğer tüm pencerelerin üzerinde sabitlenir",
        "hotkeys_label": "Kısayol Tuşları",
        "hotkeys_help": "[Ctrl+Boşluk] Başlat/Durdur, [Ctrl+Shift+Boşluk] Duraklat, [Ctrl+Shift+S] Kaydet",
        "exit_title": "Çıkış",
        "exit_confirm": "Çıkmak istediğinize emin misiniz?",
        "dont_ask": "Bir daha sorma",
        "exit_btn": "Çıkış",
        "cancel_btn": "İptal",
        "always_on_top": "Her zaman üstte",
        "auto_save": "Otomatik kaydetme",
        "nav_rec": "SES KAYDEDİCİ",
        "nav_set": "AYARLAR",
        "nav_settings": "KAYIT PARAMETRELERİ",
        "nav_about": "HAKKINDA",
        "status_ready": "KAYDA HAZIR",
        "status_recording": "KAYIT YAPILIYOR",
        "status_paused": "DURAKLATILDI",
        "btn_record": "KAYIT",
        "btn_stop": "DURDUR",
        "btn_pause": "DURAKLAT",
        "btn_resume": "DEVAM ET",
        "input_volume": "GİRİŞ SESİ",
        "device": "Cihaz",
        "format": "Format",
        "noise": "Gürültü Azaltma",
        "now_playing": "Oynatılıyor",
        "tab_settings": "UYGULAMA AYARLARI",
        "work_background": "Arka planda çalış",
        "language_label": "Dil (Language)",
        "folder_label": "Klasör",
        "bitrate": "Bit hızı",
        "frequency": "Frekans",
        "mode": "Kayıt Modu",
        "temp_rec_name": "Mevcut kayıt (kaydedilmedi)",
        "status_done": "KAYIT HAZIR",
        "status_deleted": "SİLİNDİ",
        "btn_delete": "SİL",
        "warn_save": "Önce mevcut kaydı kaydedin veya silin!",
        "player_title": "OYNATICI",
        "play_volume": "Ses",
        "btn_save": "KAYDET",
        "list_date": "TARİH",
        "list_name": "DOSYA ADI",
        "list_current": "🔴 MEVCUT KAYIT",
        "library_title": "SON KAYITLAR",
        "btn_choose_folder": "Klasör seç",
        "btn_open_explorer": "Klasörü aç",
        "tray_open": "Aç",
        "tray_exit": "Çıkış",
        "autostart": "Windows ile başlat",
        "status_save_success": "DOSYA KAYDEDİLDİ",
        "status_save_error": "KAYIT HATASI",
        "btn_cancel": "İPTAL",
        "unit_sec": "sn",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Sürüm 0.6 Beta, hatalar olabilir",
        "about_description": (
            "Sesiniz tam kontrol altında. JB Audio Recorder, kaliteye önem verenler için hafif ve güçlü bir araçtır. "
            "Karmaşık ayarları unutun: popüler formatlarda, seçilebilir bit hızı ve frekansla ses kaydedin. "
            "Dahili akıllı gürültü azaltma algoritması, sesinizi arka plan gürültülerinden temizler.\n\n"
            "Kullanışlı oynatıcı ve kütüphane. Artık sistemde dosya aramanıza gerek yok. Kaydı doğrudan uygulamada dinleyin "
            "ve kaydedip kaydetmeyeceğinize veya üzerine yazıp yazmayacağınıza karar verin. Başarılı kayıtlar, "
            "tarihe göre kolayca bulunup tek tıkla açılabilecekleri görsel bir kütüphaneye gider.\n\n"
            "İstediğiniz gibi çalışın. Kaydedici iş akışınıza mükemmel uyum sağlar: arka planda çalışabilir veya «her zaman üstte» olabilir. "
            "Kaydı kısayol tuşlarıyla yönetin ve sonuçtan endişe etmeyin — sistem, çıkışta kaydedilmemiş dosya varsa sizi uyarır."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Српски (Serbian)": {
        "reset_settings": "Поништи на подразумеване поставке",
        "reset_settings_confirm": "Да ли сте сигурни да желите да поништите све поставке на подразумеване вредности?",
        "reset_settings_success": "Поставке су успешно поништене!",
        "device_setting_label": "Уређај за снимање",
        "device_help": "Како кажу: «Ако ради — не дирај»",
        "exit_unsaved_warning": "Тренутно се снима и/или аудио није сачуван.\nДа ли сте сигурни да желите да изађете?",
        "save_path_label": "Фасцикла за чување снимака",
        "tray_settings": "Подешавања",
        "lang_help": "Могу чак и на кинеском!",
        "choose_file": "Изаберите датотеку",
        "no_file": "Нема датотеке",
        "work_background_help": "Омогућава снимање и репродукцију када је апликација минимизирана",
        "autostart_help": "Да увек буде при руци",
        "auto_save_help": "Снимак се чува директно на диск без прегледа у плејеру",
        "always_on_top_help": "Апликација ће бити фиксирана изнад свих осталих прозора",
        "hotkeys_label": "Пречице",
        "hotkeys_help": "[Ctrl+Space] Старт/Стоп, [Ctrl+Shift+Space] Пауза, [Ctrl+Shift+S] Сачувај",
        "exit_title": "Излаз",
        "exit_confirm": "Да ли сте сигурни да желите да изађете?",
        "dont_ask": "Не питај више",
        "exit_btn": "Излаз",
        "cancel_btn": "Откажи",
        "always_on_top": "Изнад свих прозора",
        "auto_save": "Аутоматско чување",
        "nav_rec": "ДИКТАФОН",
        "nav_set": "ПОДЕШАВАЊА",
        "nav_settings": "ПАРАМЕТРИ",
        "nav_about": "О ПРОГРАМУ",
        "status_ready": "СПРЕМАН",
        "status_recording": "СНИМАЊЕ У ТОКУ",
        "status_paused": "ПАУЗИРАНО",
        "btn_record": "СНИМАЈ",
        "btn_stop": "СТОП",
        "btn_pause": "ПАУЗА",
        "btn_resume": "НАСТАВИ",
        "input_volume": "ЈАЧИНА УЛАЗА",
        "device": "Уређај",
        "format": "Формат",
        "noise": "Уклањање буке",
        "now_playing": "Репродукција",
        "tab_settings": "ПОДЕШАВАЊА АПЛИКАЦИЈЕ",
        "work_background": "Рад у позадини",
        "language_label": "Језик (Language)",
        "folder_label": "Фасцикла",
        "bitrate": "Битрeјт",
        "frequency": "Фреквенција",
        "mode": "Режим",
        "temp_rec_name": "Тренутни снимак",
        "status_done": "ГОТОВО",
        "status_deleted": "ОБРИСАНО",
        "btn_delete": "ОБРИШИ",
        "warn_save": "Прво сачувајте!",
        "player_title": "ПЛЕЈЕР",
        "play_volume": "Јачина",
        "btn_save": "САЧУВАЈ",
        "list_date": "ДАТУМ",
        "list_name": "ИМЕ ДАТОТЕКЕ",
        "list_current": "🔴 ТРЕНУТНО",
        "library_title": "ПОСЛЕДЊИ СНИМЦИ",
        "btn_choose_folder": "Изабери фасциклу",
        "btn_open_explorer": "Отвори",
        "tray_open": "Отвори",
        "tray_exit": "Излаз",
        "autostart": "Покрени са Windows-ом",
        "status_save_success": "ДАТОТЕКА САЧУВАНА",
        "status_save_error": "ГРЕШКА ПРИ ЧУВАЊУ",
        "btn_cancel": "ОТКАЖИ",
        "unit_sec": "сек",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Верзија 0.6 Бета, могуће грешке",
        "about_description": (
            "Ваш звук под пуном контролом. JB Audio Recorder је лаган и моћан алат за оне којима је важан квалитет. "
            "Заборавите на сложена подешавања: снимајте аудио у популарним форматима са избором битрејта и фреквенције. "
            "Уграђени алгоритам паметног уклањања буке очистиће ваш глас од позадинских звукова.\n\n"
            "Згодан плејер и библиотека. Више не морате тражити датотеке по целом систему. Преслушајте снимак директно у апликацији "
            "и одлучите — да ли да га сачувате или преснимите. Сви успешни снимци иду у прегледну библиотеку, "
            "где их је лако пронаћи и отворити једним кликом.\n\n"
            "Радите како вам одговара. Диктафон се савршено уклапа у радни процес: може радити у позадини или бити «изнад свих прозора». "
            "Управљајте снимањем пречицама и не брините за резултат — систем ће вас упозорити на несачувану датотеку при изласку."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Қазақша (Kazakh)": {
        "reset_settings": "Әдепкі баптауларға қайтару",
        "reset_settings_confirm": "Барлық баптауларды әдепкі мәндерге қайтарғыңыз келетініне сенімдісіз бе?",
        "reset_settings_success": "Баптаулар сәтті қалпына келтірілді!",
        "device_setting_label": "Жазу құрылғысы",
        "device_help": "Айтпақшы: «Жұмыс істеп тұрса — тиіспе»",
        "exit_unsaved_warning": "Қазір жазу жүріп жатыр және/немесе аудио сақталмаған.\nШығуды растайсыз ба?",
        "save_path_label": "Жазбаларды сақтау бумасы",
        "tray_settings": "Баптаулар",
        "lang_help": "Тіпті қытайша сөйлей аламын!",
        "choose_file": "Файлды таңдау",
        "no_file": "Файл жоқ",
        "work_background_help": "Қолданба кішірейтілген кезде жазуға және тыңдауға мүмкіндік береді",
        "autostart_help": "Әрқашан қол астында болу үшін",
        "auto_save_help": "Жазба ойнатқышта алдын ала тыңдаусыз бірден дискке сақталады",
        "always_on_top_help": "Қолданба жүйедегі барлық терезелердің үстінде бекітіледі",
        "hotkeys_label": "Жылдам пернелер",
        "hotkeys_help": "[Ctrl+Space] Бастау/Тоқтату, [Ctrl+Shift+Space] Кідірту, [Ctrl+Shift+S] Сақтау",
        "exit_title": "Шығу",
        "exit_confirm": "Шығуды растайсыз ба?",
        "dont_ask": "Қайта сұрамау",
        "exit_btn": "Шығу",
        "cancel_btn": "Болдырмау",
        "always_on_top": "Терезелер үстінде",
        "auto_save": "Автосақтау",
        "nav_rec": "ДИКТОФОН",
        "nav_set": "БАПТАУЛАР",
        "nav_settings": "ПАРАМЕТРЛЕР",
        "nav_about": "ТУРАЛЫ",
        "status_ready": "ДАЙЫН",
        "status_recording": "ЖАЗУ ЖҮРІП ЖАТЫР",
        "status_paused": "КІДІРТІЛДІ",
        "btn_record": "ЖАЗУ",
        "btn_stop": "ТОҚТАТУ",
        "btn_pause": "КІДІРТУ",
        "btn_resume": "ЖАЛҒАСТЫРУ",
        "input_volume": "КІРІС ДЕҢГЕЙІ",
        "device": "Құрылғы",
        "format": "Формат",
        "noise": "Шуды басу",
        "now_playing": "Ойнатылуда",
        "tab_settings": "ҚОЛДАНБА БАПТАУЛАРЫ",
        "work_background": "Фонда жұмыс істеу",
        "language_label": "Тіл (Language)",
        "folder_label": "Бума",
        "bitrate": "Битрeйт",
        "frequency": "Жиілік",
        "mode": "Режим",
        "temp_rec_name": "Ағымдағы жазба",
        "status_done": "ДАЙЫН",
        "status_deleted": "ЖОЙЫЛДЫ",
        "btn_delete": "ЖОЮ",
        "warn_save": "Алдымен сақтаңыз!",
        "player_title": "ОЙНАТҚЫШ",
        "play_volume": "Дыбыс",
        "btn_save": "САҚТАУ",
        "list_date": "КҮНІ",
        "list_name": "ФАЙЛ АТЫ",
        "list_current": "🔴 АҒЫМДАҒЫ",
        "library_title": "Соңғы жазбалар",
        "btn_choose_folder": "Буманы таңдау",
        "btn_open_explorer": "Ашу",
        "tray_open": "Ашу",
        "tray_exit": "Шығу",
        "autostart": "Windows-пен бірге қосылу",
        "status_save_success": "ФАЙЛ САҚТАЛДЫ",
        "status_save_error": "САҚТАУ ҚАТЕСІ",
        "btn_cancel": "БОЛДЫРМАУ",
        "unit_sec": "сек",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Нұсқа 0.6 Beta, қателер болуы мүмкін",
        "about_description": (
            "Сіздің дыбысыңыз толық бақылауда. JB Audio Recorder — сапаны бағалайтындар үшін жеңіл және қуатты құрал. "
            "Күрделі баптауларды ұмытыңыз: танымал форматтарда, битрейт пен жиілікті таңдау мүмкіндігімен аудио жазыңыз. "
            "Кірістірілген зияткерлік шуды басу алгоритмі дауысыңызды бөгде дыбыстардан тазартады.\n\n"
            "Ыңғайлы ойнатқыш және кітапхана. Файлдарды бүкіл жүйеден іздеудің қажеті жоқ. Жазбаны тікелей қолданбада тыңдап, "
            "оны сақтау немесе қайта жазу туралы шешім қабылдаңыз. Барлық сәтті жазбалар көрнекі кітапханаға түседі, "
            "онда оларды оңай тауып, бір рет басу арқылы ашуға болады.\n\n"
            "Өзіңізге ыңғайлы етіп жұмыс істеңіз. Диктофон жұмыс процесіне тамаша сәйкес келеді: ол фондық режимде немесе «барлық терезелердің үстінде» жұмыс істей алады. "
            "Жазуды жылдам пернелермен басқарыңыз және нәтиже үшін алаңдамаңыз — жүйе шығу кезінде сақталмаған файл туралы ескертеді."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Português (Portuguese)": {
        "reset_settings": "Redefinir para as configurações padrão",
        "reset_settings_confirm": "Tem certeza de que deseja redefinir todas as configurações para os valores padrão?",
        "reset_settings_success": "Configurações redefinidas com sucesso!",
        "device_setting_label": "Dispositivo de gravação",
        "device_help": "Como dizem: «Em time que está ganhando não se mexe»",
        "exit_unsaved_warning": "A gravação está em andamento e/ou o áudio não foi salvo.\nTem certeza de que deseja sair?",
        "save_path_label": "Pasta para salvar gravações",
        "tray_settings": "Configurações",
        "lang_help": "Eu posso até falar chinês!",
        "choose_file": "Escolher arquivo",
        "no_file": "Nenhum arquivo",
        "work_background_help": "Permite gravar e reproduzir enquanto o aplicativo está minimizado",
        "autostart_help": "Sempre ao seu alcance",
        "auto_save_help": "A gravação é salva diretamente no disco sem prévia no player",
        "always_on_top_help": "O aplicativo ficará fixado sobre todas as outras janelas",
        "hotkeys_label": "Atalhos",
        "hotkeys_help": "[Ctrl+Espaço] Iniciar/Parar, [Ctrl+Shift+Espaço] Pausa, [Ctrl+Shift+S] Salvar",
        "exit_title": "Sair",
        "exit_confirm": "Tem certeza de que deseja sair?",
        "dont_ask": "Não perguntar novamente",
        "exit_btn": "Sair",
        "cancel_btn": "Cancelar",
        "always_on_top": "Sempre no topo",
        "auto_save": "Salvamento automático",
        "nav_rec": "GRAVADOR",
        "nav_set": "AJUSTES",
        "nav_settings": "PARÂMETROS",
        "nav_about": "SOBRE",
        "status_ready": "PRONTO",
        "status_recording": "GRAVANDO...",
        "status_paused": "PAUSA",
        "btn_record": "GRAVAR",
        "btn_stop": "PARAR",
        "btn_pause": "PAUSA",
        "btn_resume": "RETOMAR",
        "input_volume": "VOLUME DE ENTRADA",
        "device": "Dispositivo",
        "format": "Formato",
        "noise": "Redução de ruído",
        "now_playing": "Reproduzindo",
        "tab_settings": "CONFIGURAÇÕES",
        "work_background": "Trabalhar em 2º plano",
        "language_label": "Idioma (Language)",
        "folder_label": "Pasta",
        "bitrate": "Bitrate",
        "frequency": "Frequência",
        "mode": "Modo",
        "temp_rec_name": "Gravação atual",
        "status_done": "PRONTO",
        "status_deleted": "APAGADO",
        "btn_delete": "APAGAR",
        "warn_save": "Salve primeiro!",
        "player_title": "PLAYER",
        "play_volume": "Volume",
        "btn_save": "SALVAR",
        "list_date": "DATA",
        "list_name": "NOME DO ARQUIVO",
        "list_current": "🔴 ATUAL",
        "library_title": "GRAVAÇÕES RECENTES",
        "btn_choose_folder": "Escolher pasta",
        "btn_open_explorer": "Abrir pasta",
        "tray_open": "Abrir",
        "tray_exit": "Sair",
        "autostart": "Iniciar com o Windows",
        "status_save_success": "ARQUIVO SALVO",
        "status_save_error": "ERRO AO SALVAR",
        "btn_cancel": "CANCELAR",
        "unit_sec": "s",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Versão 0.6 Beta, possíveis bugs",
        "about_description": (
            "Seu som sob controle total. O JB Audio Recorder é uma ferramenta leve e poderosa para quem valoriza a qualidade. "
            "Esqueça configurações complexas: grave áudio em formatos populares com bitrate e frequência selecionáveis. "
            "O algoritmo inteligente de redução de ruído integrado limpará sua voz de sons de fundo.\n\n"
            "Player e biblioteca convenientes. Não precisa mais procurar arquivos pelo sistema. Ouça a gravação "
            "diretamente no aplicativo e decida se deseja salvá-la ou regravá-la. Todas as gravações bem-sucedidas vão para uma biblioteca visual, "
            "onde são fáceis de encontrar e abrir com um clique.\n\n"
            "Trabalhe como preferir. O gravador se adapta perfeitamente ao seu fluxo de trabalho: pode funcionar em segundo plano ou ficar «sempre no topo». "
            "Controle a gravação com teclas de atalho e não se preocupe com o resultado — o sistema avisará sobre arquivos não salvos ao sair."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Norsk (Norwegian)": {
        "reset_settings": "Redefinér til standardinnstillinger",
        "reset_settings_confirm": "Er du sikker på at du vil tilbakestille alle innstillinger til standardverdier?",
        "reset_settings_success": "Innstillinger ble tilbakestilt!",
        "device_setting_label": "Opptaksenhet",
        "device_help": "Som man sier: «Hvis det virker, ikke rør det»",
        "exit_unsaved_warning": "Opptak pågår og/eller lyd er ikke lagret.\nEr du sikker på at du vil avslutte?",
        "save_path_label": "Mappe for lagring av opptak",
        "tray_settings": "Innstillinger",
        "lang_help": "Jeg kan til og med snakke kinesisk!",
        "choose_file": "Velg fil",
        "no_file": "Ingen fil",
        "work_background_help": "Tillater opptak og avspilling mens appen er minimert",
        "autostart_help": "Alltid for hånden",
        "auto_save_help": "Opptak lagres direkte til disk uten forhåndsvisning i spilleren",
        "always_on_top_help": "Appen vil alltid ligge over alle andre vinduer",
        "hotkeys_label": "Hurtigtaster",
        "hotkeys_help": "[Ctrl+Mellomrom] Start/Stopp, [Ctrl+Shift+Mellomrom] Pause, [Ctrl+Shift+S] Lagre",
        "exit_title": "Avslutt",
        "exit_confirm": "Er du sikker på at du vil avslutte?",
        "dont_ask": "Ikke spør igjen",
        "exit_btn": "Avslutt",
        "cancel_btn": "Avbryt",
        "always_on_top": "Alltid øverst",
        "auto_save": "Automatisk lagring",
        "nav_rec": "OPPTAK",
        "nav_set": "INNSTILLINGER",
        "nav_settings": "PARAMETERE",
        "nav_about": "OM",
        "status_ready": "KLAR",
        "status_recording": "TAPER...",
        "status_paused": "PAUSE",
        "btn_record": "TA OPP",
        "btn_stop": "STOPP",
        "btn_pause": "PAUSE",
        "btn_resume": "FORTSETT",
        "input_volume": "INNGANGSVOLUM",
        "device": "Enhet",
        "format": "Format",
        "noise": "Støyreduksjon",
        "now_playing": "Spiller nå",
        "tab_settings": "APP-INNSTILLINGER",
        "work_background": "Kjør i bakgrunnen",
        "language_label": "Språk (Language)",
        "folder_label": "Mappe",
        "bitrate": "Bitrate",
        "frequency": "Frekvens",
        "mode": "Modus",
        "temp_rec_name": "Gjeldende opptak",
        "status_done": "FERDIG",
        "status_deleted": "SLETTET",
        "btn_delete": "SLETT",
        "warn_save": "Lagre først!",
        "player_title": "SPILLER",
        "play_volume": "Volum",
        "btn_save": "LAGRE",
        "list_date": "DATO",
        "list_name": "FILNAVN",
        "list_current": "🔴 GJELDENDE",
        "library_title": "SISTE OPPTAK",
        "btn_choose_folder": "Velg mappe",
        "btn_open_explorer": "Åpne mappe",
        "tray_open": "Åpne",
        "tray_exit": "Avslutt",
        "autostart": "Start med Windows",
        "status_save_success": "FIL LAGRET",
        "status_save_error": "LAGRINGSFEIL",
        "btn_cancel": "AVBRYT",
        "unit_sec": "sek",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Versjon 0.6 Beta, mulige feil",
        "about_description": (
            "Lyden din under full kontroll. JB Audio Recorder er et lett og kraftig verktøy for de som verdsetter kvalitet. "
            "Glem kompliserte innstillinger: ta opp lyd i populære formater med valgfri bitrate og frekvens. "
            "Den innebygde intelligente støyreduksjonsalgoritmen renser stemmen din for bakgrunnsstøy.\n\n"
            "Praktisk spiller og bibliotek. Du trenger ikke lenger lete etter filer i systemet. Lytt til opptaket "
            "direkte i appen og bestem om du vil lagre det eller ta det opp på nytt. Alle vellykkede opptak havner i et visuelt bibliotek, "
            "hvor de er enkle å finne og åpne med ett klikk.\n\n"
            "Jobb som du vil. Opptakeren passer perfekt inn i arbeidsflyten din: den kan kjøre i bakgrunnen eller ligge «alltid øverst». "
            "Styr opptaket med hurtigtaster og ikke bekymre deg for resultatet — systemet vil varsle deg om ulagrede filer når du avslutter."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Français (French)": {
        "reset_settings": "Réinitialiser les paramètres par défaut",
        "reset_settings_confirm": "Êtes-vous sûr de vouloir réinitialiser tous les paramètres aux valeurs par défaut ?",
        "reset_settings_success": "Paramètres réinitialisés avec succès !",
        "device_setting_label": "Périphérique d'enregistrement",
        "device_help": "Comme on dit : « Si ça marche, n'y touchez pas »",
        "exit_unsaved_warning": "Un enregistrement est en cours et/ou l'audio n'a pas encore été sauvegardé.\nÊtes-vous sûr de vouloir quitter ?",
        "save_path_label": "Dossier pour enregistrer les enregistrements",
        "tray_settings": "Paramètres",
        "lang_help": "Je peux même parler chinois!",
        "choose_file": "Choisir un fichier",
        "work_background_help": "Permet l'enregistrement et la lecture lorsque l'application est réduite",
        "autostart_help": "Toujours à portée de main",
        "auto_save_help": "L'enregistrement est enregistré directement sur le disque sans prévisualisation",
        "always_on_top_help": "L'application restera au premier plan par rapport aux autres fenêtres",
        "hotkeys_label": "Raccourcis clavier",
        "hotkeys_help": "[Ctrl+Espace] Démarrer/Arrêter, [Ctrl+Maj+Espace] Pause, [Ctrl+Maj+S] Enregistrer",
        "exit_title": "Quitter",
        "exit_confirm": "Voulez-vous vraiment quitter ?",
        "dont_ask": "Ne plus me demander",
        "exit_btn": "Quitter",
        "cancel_btn": "Annuler",
        "always_on_top": "Toujours au premier plan",
        "auto_save": "Enregistrement auto",
        "nav_rec": "ENREGISTREUR",
        "nav_set": "PARAMÈTRES",
        "nav_settings": "RÉGLAGES",
        "nav_about": "À PROPOS",
        "status_ready": "PRÊT",
        "status_recording": "ENREGISTREMENT...",
        "status_paused": "PAUSE",
        "btn_record": "ENREGISTRER",
        "btn_stop": "STOP",
        "btn_pause": "PAUSE",
        "btn_resume": "REPRENDRE",
        "input_volume": "VOLUME",
        "device": "Appareil",
        "format": "Format",
        "noise": "Réduction de bruit",
        "now_playing": "Lecture",
        "no_file": "Pas de fichier",
        "tab_settings": "RÉGLAGES APPLI",
        "work_background": "Arrière-plan",
        "language_label": "Langue (Language)",
        "folder_label": "Dossier",
        "bitrate": "Bitrate",
        "frequency": "Fréquence",
        "mode": "Mode",
        "temp_rec_name": "Enregistrement actuel",
        "status_done": "PRÊT",
        "status_deleted": "SUPPRIMÉ",
        "btn_delete": "SUPPRIMER",
        "warn_save": "Enregistrez d'abord!",
        "player_title": "LECTEUR",
        "play_volume": "Volume",
        "btn_save": "SAUVEGARDER",
        "list_date": "DATE",
        "list_name": "NOM DU FICHIER",
        "list_current": "🔴 ACTUEL",
        "library_title": "ENREGISTREMENTS RÉCENTS",
        "btn_choose_folder": "Choisir dossier",
        "btn_open_explorer": "Explorateur",
        "tray_open": "Ouvrir",
        "tray_exit": "Quitter",
        "autostart": "Lancer avec Windows",
        "status_save_success": "FICHIER ENREGISTRÉ",
        "status_save_error": "ERREUR D'ENREGISTREMENT",
        "btn_cancel": "ANNULER",
        "unit_sec": "sec",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Version 0.6 Beta, bugs possibles",
        "about_description": (
            "Votre son sous contrôle total. JB Audio Recorder est un outil léger et puissant pour ceux qui apprécient la qualité. "
            "Oubliez les paramètres complexes : enregistrez de l'audio dans des formats populaires avec un débit binaire et une fréquence sélectionnables. "
            "L'algorithme de réduction de bruit intelligent intégré nettoie votre voix des bruits de fond.\n\n"
            "Lecteur et bibliothèque pratiques. Plus besoin de chercher des fichiers dans tout le système. Écoutez l'enregistrement "
            "directement dans l'application et décidez si vous voulez l'enregistrer ou l'écraser. Tous les enregistrements réussis vont dans une bibliothèque visuelle, "
            "où ils sont faciles à trouver et à ouvrir en un clic.\n\n"
            "Travaillez comme vous le souhaitez. L'enregistreur s'intègre parfaitement à votre flux de travail : il peut fonctionner en arrière-plan ou rester « toujours au premier plan ». "
            "Contrôlez l'enregistrement avec des raccourcis clavier et ne vous inquiétez pas du résultat — le système vous avertira des fichiers non enregistrés à la sortie."
        ),
        "about_links": "GitHub :",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Беларуская (Belarusian)": {
        "reset_settings": "Скінуць да стандартных налад",
        "reset_settings_confirm": "Вы ўпэўненыя, што хочаце скінуць усе налады да стандартных значэнняў?",
        "reset_settings_success": "Налады паспяхова скінуты!",
        "device_setting_label": "Прылада для запісу",
        "device_help": "Як кажуць: «Калі працуе — не чапай»",
        "exit_unsaved_warning": "На дадзены момант вядзецца запіс і/або аўдыё не было захавана.\nВы сапраўды хочаце выйсці?",
        "save_path_label": "Папка для захавання запісаў",
        "tray_settings": "Налады",
        "lang_help": "Магу нават па-кітайску!",
        "choose_file": "Выберыце файл",
        "work_background_help": "Дазваляе рабіць запісы і слухаць аўдыё, калі праграма звернутая",
        "autostart_help": "Каб заўсёды быць пад рукой",
        "auto_save_help": "Запіс захаваецца адразу на дыск без папярэдняга прайгравання ў плееры",
        "always_on_top_help": "Праграма будзе замацаваная па-над усімі іншымі вокнамі сістэмы",
        "hotkeys_label": "Гарачыя клавішы",
        "hotkeys_help": "[Ctrl+Прабел] Старт/Стоп, [Ctrl+Shift+Прабел] Паўза, [Ctrl+Shift+S] Захаваць",
        "exit_title": "Выхад",
        "exit_confirm": "Вы сапраўды хочаце выйсці?",
        "dont_ask": "Больш не пытацца",
        "exit_btn": "Выхад",
        "cancel_btn": "Адмена",
        "always_on_top": "Па-над усімі вокнамі",
        "auto_save": "Аўтаматычнае захаванне",
        "nav_rec": "ДЫКТАФОН",
        "nav_set": "НАЛАДЫ",
        "nav_settings": "ПАРАМЕТРЫ ЗАПІСУ",
        "nav_about": "АБ ПРАГРАМЕ",
        "status_ready": "ГАТОВЫ ДА ЗАПІСУ",
        "status_recording": "ІДЗЕ ЗАПІС",
        "status_paused": "ЗАПІС ПРЫПЫНЕНЫ",
        "btn_record": "ЗАПІС",
        "btn_stop": "СТОП",
        "btn_pause": "ПАЎЗА",
        "btn_resume": "ПРАЦЯГНУЦЬ",
        "input_volume": "ГУЧНАСЦЬ УВАХОДУ",
        "device": "Прылада",
        "format": "Фармат",
        "noise": "Шумападаўленне",
        "now_playing": "Прайграваецца",
        "no_file": "Няма файла",
        "tab_settings": "ПАРАМЕТРЫ ПРАГРАМЫ",
        "work_background": "Працаваць у фоне",
        "language_label": "Мова (Language)",
        "folder_label": "Папка",
        "bitrate": "Бітрэйт",
        "frequency": "Частота",
        "mode": "Рэжым запісу",
        "temp_rec_name": "Бягучы запіс",
        "status_done": "ЗАПІС ГАТОВЫ",
        "status_deleted": "ВЫДАЛЕНА",
        "btn_delete": "ВЫДАЛІЦЬ",
        "warn_save": "Спачатку захавайце альбо выдаліце запіс!",
        "player_title": "ПЛЭЕР",
        "play_volume": "Гучнасць",
        "btn_save": "ЗАХАВАЦЬ",
        "list_date": "ДАТА",
        "list_name": "ІМЯ ФАЙЛА",
        "list_current": "🔴 БЯГУЧЫ ЗАПІС",
        "library_title": "АПОШНІЯ ЗАПІСЫ",
        "btn_choose_folder": "Выбраць папку",
        "btn_open_explorer": "Адкрыць папку",
        "tray_open": "Адкрыць",
        "tray_exit": "Выхад",
        "autostart": "Запускаць разам з Windows",
        "status_save_success": "ФАЙЛ ЗАХАВАНЫ",
        "status_save_error": "ПАМЫЛКА ЗАХАВАННЯ",
        "btn_cancel": "АДМЯНІЦЬ",
        "unit_sec": "сек",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Версія 0.6 Beta, магчымыя памылкі",
        "about_description": (
            "Ваш гук пад поўным кантролем. JB Audio Recorder — гэта лёгкі і магутны інструмент для тых, хто шануе якасць. "
            "Забудзьцеся пра складаныя налады: запісвайце аўдыё ў папулярных фарматах з выбарам бітрэйту і частаты. "
            "Убудаваны алгарытм інтэлектуальнага шумападаўлення ачысціць голас ад фонавых гукаў.\n\n"
            "Зручны плэер і бібліятэка. Больш не трэба шукаць файлы па ўсёй сістэме. Прама ў праграме праслухайце запіс "
            "і вырашыце — захаваць яго ці перазапісаць. Усе ўдалыя запісы трапляюць у наглядную бібліятэку, "
            "дзе іх лёгка знайсці і адкрыць адным клікам.\n\n"
            "Працуйце так, як вам зручна. Дыктафон можа працаваць у фонавым рэжыме ці быць заўсёды пад рукой «па-над усімі вокнамі». "
            "Кіруйце запісам гарачымі клавішамі і не хвалюйцеся за вынік — сістэма папярэдзіць пра не захаваны файл пры выхадзе."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Українська (Ukrainian)": {
        "reset_settings": "Скинути до стандартних налаштувань",
        "reset_settings_confirm": "Ви впевнені, що хочете скинути всі налаштування до стандартних значень?",
        "reset_settings_success": "Налаштування успішно сброшены!",
        "device_setting_label": "Пристрій запису",
        "device_help": "Як кажуть: «Якщо працює — не чіпай»",
        "exit_unsaved_warning": "На даний момент ведеться запис і/або аудіо не було збережено.\nВи точно хочете вийти?",
        "save_path_label": "Папка для збереження записів",
        "tray_settings": "Налаштування",
        "lang_help": "Можу навіть китайською!",
        "choose_file": "Виберіть файл",
        "work_background_help": "Дозволяє робити записи та прослуховувати аудіо, коли програму згорнуто",
        "autostart_help": "Щоб завжди бути під рукою",
        "auto_save_help": "Запис збережеться одразу на диск без попереднього прослуховування в програвачі",
        "always_on_top_help": "Програма буде закріплена поверх усіх інших вікон у системі",
        "hotkeys_label": "Гарячі клавіші",
        "hotkeys_help": "[Ctrl+Пробіл] Старт/Стоп, [Ctrl+Shift+Пробіл] Пауза, [Ctrl+Shift+S] Зберегти",
        "exit_title": "Вихід",
        "exit_confirm": "Ви дійсно бажаєте вийти?",
        "dont_ask": "Більше не питати",
        "exit_btn": "Вихід",
        "cancel_btn": "Скасувати",
        "always_on_top": "Поверх всіх вікон",
        "auto_save": "Автоматичне збереження",
        "nav_rec": "ДИКТОФОН",
        "nav_set": "НАЛАШТУВАННЯ",
        "nav_settings": "ПАРАМЕТРИ ЗАПИСУ",
        "nav_about": "ПРО ПРОГРАМУ",
        "status_ready": "ГОТОВИЙ ДО ЗАПИСУ",
        "status_recording": "ЙДЕ ЗАПИС",
        "status_paused": "ЗАПИС ПРИЗУПИНЕНО",
        "btn_record": "ЗАПИС",
        "btn_stop": "СТОП",
        "btn_pause": "ПАУЗА",
        "btn_resume": "ПРОДОВЖИТИ",
        "input_volume": "ГУЧНІСТЬ ВХОДУ",
        "device": "Пристрій",
        "format": "Формат",
        "noise": "Шумозаглушення",
        "now_playing": "Відтворюється",
        "no_file": "Немає файлу",
        "tab_settings": "ПАРАМЕТРИ ПРОГРАМИ",
        "work_background": "Працювати у фоні",
        "language_label": "Мова (Language)",
        "folder_label": "Папка",
        "bitrate": "Бітрейт",
        "frequency": "Частота",
        "mode": "Режим запису",
        "temp_rec_name": "Поточний запис",
        "status_done": "ЗАПИС ГОТОВИЙ",
        "status_deleted": "ВИДАЛЕНО",
        "btn_delete": "ВИДАЛИТИ",
        "warn_save": "Спочатку збережіть або видаліть запис!",
        "player_title": "ПЛЕЄР",
        "play_volume": "Гучність",
        "btn_save": "ЗБЕРЕГТИ",
        "list_date": "ДАТА",
        "list_name": "ІМ'Я ФАЙЛУ",
        "list_current": "🔴 ПОТОЧНИЙ ЗАПИС",
        "library_title": "ОСТАННІ ЗАПИСИ",
        "btn_choose_folder": "Вибрати папку",
        "btn_open_explorer": "Відкрити папку",
        "tray_open": "Відкрити",
        "tray_exit": "Вихід",
        "autostart": "Запускати разом з Windows",
        "status_save_success": "ФАЙЛ ЗБЕРЕЖЕНО",
        "status_save_error": "ПОМИЛКА ЗБЕРЕЖЕННЯ",
        "btn_cancel": "СКАСУВАТИ",
        "unit_sec": "сек",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Версія 0.6 Beta, можливі баги",
        "about_description": (
            "Ваш звук під повним контролем. JB Audio Recorder — це легкий і потужний інструмент для тих, кому важлива якість. "
            "Забудьте про складні налаштування: записуйте аудіо в популярних форматах з вибором бітрейту та частоти. "
            "Вбудований алгоритм інтелектуального шумозаглушення очистить голос від фонових звуків.\n\n"
            "Зручний плеєр і бібліотека. Більше не потрібно шукати файли по всій системі. Прямо в додатку прослухайте запис "
            "і вирішіть — зберегти його або перезаписати. Всі вдалі записи потрапляють в наочну бібліотеку, "
            "де їх легко знайти і відкрити одним кліком.\n\n"
            "Працюйте так, як вам зручно. Диктофон може працювати у фоновому режимі або бути завжди під рукою «поверх всіх вікон». "
            "Керуйте записом гарячими клавішами і не хвилюйтеся за результат — система попередить про незбережений файл при виході."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Deutsch (German)": {
        "reset_settings": "Auf Standardeinstellungen zurücksetzen",
        "reset_settings_confirm": "Sind Sie sicher, dass Sie alle Einstellungen auf die Standardwerte zurücksetzen möchten?",
        "reset_settings_success": "Einstellungen erfolgreich zurückgesetzt!",
        "device_setting_label": "Aufnahmegerät",
        "device_help": "Wie man so schön sagt: „Wenn es funktioniert, nicht anfassen“",
        "exit_unsaved_warning": "Die Aufnahme läuft und/oder die Audiodatei wurde noch nicht gespeichert.\nMöchten Sie wirklich beenden?",
        "save_path_label": "Ordner zum Speichern der Aufnahmen",
        "tray_settings": "Einstellungen",
        "lang_help": "Ich kann sogar Chinesisch sprechen!",
        "choose_file": "Datei auswählen",
        "work_background_help": "Ermöglicht das Aufnehmen und Abspielen, wenn die App minimiert ist",
        "autostart_help": "Immer griffbereit",
        "auto_save_help": "Die Aufnahme wird direkt auf die Festplatte gespeichert, ohne dass sie zuvor im Player abgespielt werden muss",
        "always_on_top_help": "Die Anwendung wird über allen anderen Fenstern in der Systemleiste angezeigt",
        "hotkeys_label": "Tastenkürzel",
        "hotkeys_help": "[Strg+Leertaste] Start/Stopp, [Strg+Umschalt+Leertaste] Pause, [Strg+Umschalt+S] Speichern",
        "exit_title": "Beenden",
        "exit_confirm": "Möchten Sie wirklich beenden?",
        "dont_ask": "Nicht mehr fragen",
        "exit_btn": "Beenden",
        "cancel_btn": "Abbrechen",
        "always_on_top": "Immer im Vordergrund",
        "auto_save": "Automatisches Speichern",
        "nav_rec": "RECORDER",
        "nav_set": "EINSTELLUNGEN",
        "nav_settings": "PARAMETER",
        "nav_about": "ÜBER",
        "status_ready": "BEREIT",
        "status_recording": "AUFNAHME...",
        "status_paused": "PAUSE",
        "btn_record": "AUFNAHME",
        "btn_stop": "STOPP",
        "btn_pause": "PAUSE",
        "btn_resume": "WEITER",
        "input_volume": "LAUTSTÄRKE",
        "device": "Gerät",
        "format": "Format",
        "noise": "Rauschunterdrückung",
        "now_playing": "Wiedergabe",
        "no_file": "Keine Datei",
        "tab_settings": "APP-EINSTELLUNGEN",
        "work_background": "Hintergrund",
        "language_label": "Sprache (Language)",
        "folder_label": "Ordner",
        "bitrate": "Bitrate",
        "frequency": "Frequenz",
        "mode": "Modus",
        "temp_rec_name": "Aktuelle Aufnahme",
        "status_done": "BEREIT",
        "status_deleted": "GELÖSCHT",
        "btn_delete": "LÖSCHEN",
        "warn_save": "Zuerst speichern!",
        "player_title": "PLAYER",
        "play_volume": "Lautstärke",
        "btn_save": "SPEICHERN",
        "list_date": "DATUM",
        "list_name": "DATEINAME",
        "list_current": "🔴 AKTUELL",
        "library_title": "NEUESTE AUFNAHMEN",
        "btn_choose_folder": "Ordner wählen",
        "btn_open_explorer": "Explorer",
        "tray_open": "Öffnen",
        "tray_exit": "Beenden",
        "autostart": "Mit Windows starten",
        "status_save_success": "DATEI GESPEICHERT",
        "status_save_error": "SPEICHERFEHLER",
        "btn_cancel": "ABBRECHEN",
        "unit_sec": "Sek",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Version 0.6 Beta, mögliche Fehler",
        "about_description": (
            "Ihr Sound unter voller Kontrolle. JB Audio Recorder ist ein leichtes und leistungsstarkes Werkzeug für diejenigen, die Qualität schätzen. "
            "Vergessen Sie komplexe Einstellungen: Nehmen Sie Audio in gängigen Formaten mit wählbarer Bitrate und Frequenz auf. "
            "Der integrierte intelligente Rauschunterdrückungsalgorithmus reinigt Ihre Stimme von Hintergrundgeräuschen.\n\n"
            "Praktischer Player und Bibliothek. Sie müssen nicht mehr im ganzen System nach Dateien suchen. Hören Sie die Aufnahme "
            "direkt in der App an und entscheiden Sie, ob Sie sie speichern oder überschreiben möchten. Alle erfolgreichen Aufnahmen landen in einer visuellen Bibliothek, "
            "wo sie leicht zu finden und mit einem Klick zu öffnen sind.\n\n"
            "Arbeiten Sie, wie Sie möchten. Der Recorder fügt sich perfekt in Ihren Arbeitsablauf ein: Er kann im Hintergrund laufen oder „immer im Vordergrund“ sein. "
            "Steuern Sie die Aufnahme mit Hotkeys und sorgen Sie sich nicht um das Ergebnis – das System warnt Sie beim Beenden vor nicht gespeicherten Dateien."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Polski (Polish)": {
        "reset_settings": "Zresetuj do ustawień domyślnych",
        "reset_settings_confirm": "Czy na pewno chcesz zresetować wszystkie ustawienia do wartości domyślnych?",
        "reset_settings_success": "Ustawienia zostały zresetowane!",
        "device_setting_label": "Urządzenie nagrywające",
        "device_help": "Jak to mówią: „Jeśli działa, nie ruszaj”",
        "exit_unsaved_warning": "Obecnie trwa nagrywanie i/lub audio nie zostało zapisane.\nCzy na pewno chcesz wyjść?",
        "save_path_label": "Folder do zapisywania nagrań",
        "tray_settings": "Ustawienia",
        "lang_help": "Mogę nawet mówić po chińsku!",
        "choose_file": "Wybierz plik",
        "work_background_help": "Umożliwia nagrywanie i odtwarzanie, gdy aplikacja jest zminimalizowana",
        "autostart_help": "Zawsze pod ręką",
        "auto_save_help": "Nagranie zostanie od razu zapisane na dysk bez wstępnego odsłuchania w odtwarzaczu",
        "always_on_top_help": "Aplikacja będzie utrzymywana na wierzchu wszystkich innych okien",
        "hotkeys_label": "Skróty klawiaturowe",
        "hotkeys_help": "[Ctrl+Spacja] Start/Stop, [Ctrl+Shift+Spacja] Pauza, [Ctrl+Shift+S] Zapisz",
        "exit_title": "Wyjście",
        "exit_confirm": "Czy na pewno chcesz wyjść?",
        "dont_ask": "Nie pytaj ponownie",
        "exit_btn": "Wyjście",
        "cancel_btn": "Anuluj",
        "always_on_top": "Zawsze na wierzchu",
        "auto_save": "Automatyczne zapisywanie",
        "nav_rec": "REJESTRATOR",
        "nav_set": "USTAWIENIA",
        "nav_settings": "PARAMETRY",
        "nav_about": "O PROGRAMIE",
        "status_ready": "GOTOWY",
        "status_recording": "NAGRYWANIE...",
        "status_paused": "PAUZA",
        "btn_record": "NAGRAJ",
        "btn_stop": "STOP",
        "btn_pause": "PAUZA",
        "btn_resume": "WZNÓW",
        "input_volume": "GŁOŚNOŚĆ",
        "device": "Urządzenie",
        "format": "Format",
        "noise": "Redukcja szumów",
        "now_playing": "Odtwarzanie",
        "no_file": "Brak pliku",
        "tab_settings": "USTAWIENIA APLIKACJI",
        "work_background": "Praca w tle",
        "language_label": "Język (Language)",
        "folder_label": "Folder",
        "bitrate": "Bitrate",
        "frequency": "Częstotliwość",
        "mode": "Tryb",
        "temp_rec_name": "Bieżące nagranie",
        "status_done": "GOTOWE",
        "status_deleted": "USUNIĘTO",
        "btn_delete": "USUŃ",
        "warn_save": "Najpierw zapisz!",
        "player_title": "ODTWARZACZ",
        "play_volume": "Głośność",
        "btn_save": "ZAPISZ",
        "list_date": "DATA",
        "list_name": "NAZWA",
        "list_current": "🔴 BIEŻĄCE",
        "library_title": "Najnowsze nagrania",
        "btn_choose_folder": "Wybierz folder",
        "btn_open_explorer": "Eksplorator",
        "tray_open": "Otwórz",
        "tray_exit": "Wyjdź",
        "autostart": "Uruchamiaj z systemem Windows",
        "status_save_success": "PLIK ZAPISANY",
        "status_save_error": "BŁĄD ZAPISU",
        "btn_cancel": "ANULUJ",
        "unit_sec": "s",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Wersja 0.6 Beta, możliwe błędy",
        "about_description": (
            "Twój dźwięk pod pełną kontrolą. JB Audio Recorder to lekkie i potężne narzędzie dla tych, którzy cenią jakość. "
            "Zapomnij o skomplikowanych ustawieniach: nagrywaj audio w popularnych formatach z wyborem bitrate'u i częstotliwości. "
            "Wbudowany algorytm inteligentnej redukcji szumów oczyści Twój głos z dźwięków tła.\n\n"
            "Wygodny odtwarzacz i biblioteka. Nie musisz już szukać plików w całym systemie. Posłuchaj nagrania "
            "bezpośrednio w aplikacji i zdecyduj — zapisać je czy nagrać ponownie. Wszystkie udane nagrania trafiają do przejrzystej biblioteki, "
            "gdzie łatwo je znaleźć i otworzyć jednym kliknięciem.\n\n"
            "Pracuj tak, jak Ci wygodnie. Dyktafon idealnie wpisuje się w Twój proces pracy: może działać w tle lub być zawsze „na wierzchu”. "
            "Steruj nagrywaniem za pomocą skrótów klawiszowych i nie martw się o wynik — system ostrzeże Cię o niezapisanym pliku przy wyjściu."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Español (Spanish)": {
        "reset_settings": "Restablecer a la configuración predeterminada",
        "reset_settings_confirm": "¿Estás seguro de que quieres restablecer todas las configuraciones a los valores predeterminados?",
        "reset_settings_success": "¡Configuraciones restablecidas con éxito!",
        "device_setting_label": "Dispositivo de grabación",
        "device_help": "Como dicen: «Si funciona, no lo toques»",
        "exit_unsaved_warning": "Actualmente se está grabando y/o el audio no se ha guardado.\n¿Estás seguro de que quieres salir?",
        "save_path_label": "Carpeta para guardar las grabaciones",
        "tray_settings": "Configuración",
        "lang_help": "¡Incluso puedo hablar chino!",
        "choose_file": "Elegir archivo",
        "work_background_help": "Permite grabar y reproducir mientras la aplicación está minimizada",
        "autostart_help": "Siempre a mano",
        "auto_save_help": "La grabación se guarda directamente en el disco sin previsualización en el reproductor",
        "always_on_top_help": "La aplicación permanecerá encima de todas las demás ventanas",
        "hotkeys_label": "Atajos de teclado",
        "hotkeys_help": "[Ctrl+Espacio] Iniciar/Detener, [Ctrl+Mayús+Espacio] Pausa, [Ctrl+Mayús+S] Guardar",
        "exit_title": "Salir",
        "exit_confirm": "¿Estás seguro de que quieres salir?",
        "dont_ask": "No volver a preguntar",
        "exit_btn": "Salir",
        "cancel_btn": "Cancelar",
        "always_on_top": "Siempre encima",
        "auto_save": "Guardado automático",
        "nav_rec": "GRABADORA",
        "nav_set": "AJUSTES",
        "nav_settings": "PARÁMETROS",
        "nav_about": "ACERCA DE",
        "status_ready": "LISTO",
        "status_recording": "GRABANDO...",
        "status_paused": "PAUSA",
        "btn_record": "GRABAR",
        "btn_stop": "PARAR",
        "btn_pause": "PAUSA",
        "btn_resume": "CONTINUAR",
        "input_volume": "VOLUMEN",
        "device": "Dispositivo",
        "format": "Formato",
        "noise": "Reducción de ruido",
        "now_playing": "Reproduciendo",
        "no_file": "Sin archivo",
        "tab_settings": "AJUSTES DE LA APP",
        "work_background": "Segundo plano",
        "language_label": "Idioma (Language)",
        "folder_label": "Carpeta",
        "bitrate": "Bitrate",
        "frequency": "Frecuencia",
        "mode": "Modo",
        "temp_rec_name": "Grabación actual",
        "status_done": "LISTO",
        "status_deleted": "ELIMINADO",
        "btn_delete": "ELIMINAR",
        "warn_save": "¡Guarde primero!",
        "player_title": "REPRODUCTOR",
        "play_volume": "Volumen",
        "btn_save": "GUARDAR",
        "list_date": "FECHA",
        "list_name": "ARCHIVO",
        "list_current": "🔴 ACTUAL",
        "library_title": "GRABACIONES RECIENTES",
        "btn_choose_folder": "Elegir carpeta",
        "btn_open_explorer": "Explorador",
        "tray_open": "Abrir",
        "tray_exit": "Salir",
        "autostart": "Iniciar con Windows",
        "status_save_success": "ARCHIVO GUARDADO",
        "status_save_error": "ERROR AL GUARDAR",
        "btn_cancel": "CANCELAR",
        "unit_sec": "seg",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Versión 0.6 Beta, posibles errores",
        "about_description": (
            "Tu sonido bajo control total. JB Audio Recorder es una herramienta ligera y potente para quienes valoran la calidad. "
            "Olvida las configuraciones complejas: graba audio en formatos populares con bitrate y frecuencia seleccionables. "
            "El algoritmo inteligente de reducción de ruido integrado limpiará tu voz de los sonidos de fondo.\n\n"
            "Reproductor y biblioteca convenientes. Ya no necesitas buscar archivos por todo el sistema. Escucha la grabación "
            "directamente en la aplicación y decide si guardarla o regrabarla. Todas las grabaciones exitosas van a una biblioteca visual, "
            "donde son fáciles de encontrar y abrir con un clic.\n\n"
            "Trabaja como prefieras. La grabadora se adapta perfectamente a tu flujo de trabajo: puede funcionar en segundo plano o estar «siempre encima». "
            "Controla la grabación con atajos de teclado y no te preocupes por el resultado — el sistema te avisará sobre archivos no guardados al salir."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "Čeština (Czech)": {
        "reset_settings": "Obnovit výchozí nastavení",
        "reset_settings_confirm": "Opravdu chcete obnovit všechna nastavení na výchozí hodnoty?",
        "reset_settings_success": "Nastavení úspěšně obnoveno!",
        "device_setting_label": "Nahrávací zařízení",
        "device_help": "Jak se říká: „Když to funguje, nesahej na to“",
        "exit_unsaved_warning": "Momentálně probíhá nahrávání a/nebo audio nebylo uloženo.\nOpravdu chcete skončit?",
        "save_path_label": "Složka pro ukládání nahrávek",
        "tray_settings": "Nastavení",
        "lang_help": "Mohu dokonce mluvit čínsky!",
        "choose_file": "Vyberte soubor",
        "work_background_help": "Umožňuje nahrávání a přehrávání, když je aplikace minimalizována",
        "autostart_help": "Vždy po ruce",
        "auto_save_help": "Nahrávka se uloží přímo na disk bez náhledu v přehrávači",
        "always_on_top_help": "Aplikace bude vždy navrchu nad všemi ostatními okny",
        "hotkeys_label": "Klávesové zkratky",
        "hotkeys_help": "[Ctrl+Mezerník] Start/Stop, [Ctrl+Shift+Mezerník] Pauza, [Ctrl+Shift+S] Uložit",
        "exit_title": "Ukončit",
        "exit_confirm": "Opravdu chcete skončit?",
        "dont_ask": "Příště se neptat",
        "exit_btn": "Ukončit",
        "cancel_btn": "Zrušit",
        "always_on_top": "Vždy navrchu",
        "auto_save": "Automatické ukládání",
        "nav_rec": "REKORDÉR",
        "nav_set": "NASTAVENÍ",
        "nav_settings": "PARAMETRY",
        "nav_about": "O APLIKACI",
        "status_ready": "PŘIPRAVEN",
        "status_recording": "NAHRÁVÁM...",
        "status_paused": "PAUZA",
        "btn_record": "NAHRÁVAT",
        "btn_stop": "STOP",
        "btn_pause": "PAUZA",
        "btn_resume": "POKRAČOVAT",
        "input_volume": "HLASITOST",
        "device": "Zařízení",
        "format": "Formát",
        "noise": "Redukce šumu",
        "now_playing": "Přehrává se",
        "no_file": "Žádný soubor",
        "tab_settings": "NASTAVENÍ APLIKACE",
        "work_background": "Pozadí",
        "language_label": "Jazyk (Language)",
        "folder_label": "Složka",
        "bitrate": "Bitrate",
        "frequency": "Frekvence",
        "mode": "Režim",
        "temp_rec_name": "Aktuální nahrávka",
        "status_done": "HOTOVO",
        "status_deleted": "SMAZÁNO",
        "btn_delete": "SMAZAT",
        "warn_save": "Nejdříve uložte!",
        "player_title": "PŘEHRÁVAČ",
        "play_volume": "Hlasitost",
        "btn_save": "ULOŽIT",
        "list_date": "DATUM",
        "list_name": "NÁZEV",
        "list_current": "🔴 AKTUÁLNÍ",
        "library_title": "NEJNOVĚJŠÍ NAHRÁVKY",
        "btn_choose_folder": "Vybrat složku",
        "btn_open_explorer": "Průzkumník",
        "tray_open": "Otevřít",
        "tray_exit": "Ukončit",
        "autostart": "Spustit se systémem Windows",
        "status_save_success": "SOUBOR ULOŽEN",
        "status_save_error": "CHYBA UKLÁDÁNÍ",
        "btn_cancel": "ZRUŠIT",
        "unit_sec": "s",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "Verze 0.6 Beta, možné chyby",
        "about_description": (
            "Váš zvuk plně pod kontrolou. JB Audio Recorder je lehký a výkonný nástroj pro ty, kteří si cení kvality. "
            "Zapomeňte na složitá nastavení: nahrávejte zvuk v populárních formátech s volitelným datovým tokem a frekvencí. "
            "Vestavěný algoritmus inteligentní redukce šumu vyčistí váš hlas od zvuků na pozadí.\n\n"
            "Pohodlný přehrávač a knihovna. Už nemusíte hledat soubory v celém systému. Poslechněte si nahrávku "
            "přímo v aplikaci a rozhodněte se, zda ji uložit nebo přehrát. Všechny úspěšné nahrávky putují do přehledné knihovny, "
            "kde je snadno najdete a otevřete jedním kliknutím.\n\n"
            "Pracujte, jak vám to vyhovuje. Rekordér se dokonale hodí do vašeho pracovního postupu: může běžet na pozadí nebo být „vždy navrchu“. "
            "Ovládejte nahrávání pomocí klávesových zkratek a nedělejte si starosti o výsledek — systém vás při ukončení upozorní na neuložený soubor."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "简体中文 (Chinese)": {
        "reset_settings": "恢复默认设置",
        "reset_settings_confirm": "您确定要将所有设置恢复为默认值吗？",
        "reset_settings_success": "设置已成功恢复为默认值！",
        "device_setting_label": "录音设备",
        "device_help": "俗话说：“既然能用，就别乱动”",
        "exit_unsaved_warning": "当前正在录音和/或音频未保存。\n您确定要退出吗？",
        "save_path_label": "录音保存文件夹",
        "tray_settings": "设置",
        "lang_help": "我甚至会说法语！",
        "choose_file": "选择文件",
        "work_background_help": "允许在应用程序最小化时进行录音和播放",
        "autostart_help": "始终触手可及",
        "auto_save_help": "录音将直接保存到磁盘，无需在播放器中预览",
        "always_on_top_help": "应用程序将始终置顶于所有其他窗口之上",
        "hotkeys_label": "快捷键",
        "hotkeys_help": "[Ctrl+空格] 开始/停止, [Ctrl+Shift+空格] 暂停, [Ctrl+Shift+S] 保存",
        "exit_title": "退出",
        "exit_confirm": "您确定要退出吗？",
        "dont_ask": "不再询问",
        "exit_btn": "退出",
        "cancel_btn": "取消",
        "always_on_top": "置顶显示",
        "auto_save": "自动保存",
        "nav_rec": "录音机",
        "nav_set": "设置",
        "nav_settings": "录音参数",
        "nav_about": "关于",
        "status_ready": "准备就绪",
        "status_recording": "正在录音...",
        "status_paused": "暂停",
        "btn_record": "录音",
        "btn_stop": "停止",
        "btn_pause": "暂停",
        "btn_resume": "继续",
        "input_volume": "音量",
        "device": "设备",
        "format": "格式",
        "noise": "降噪",
        "now_playing": "正在播放",
        "no_file": "无文件",
        "tab_settings": "应用设置",
        "work_background": "后台运行",
        "language_label": "语言 (Language)",
        "folder_label": "文件夹",
        "bitrate": "比特率",
        "frequency": "频率",
        "mode": "模式",
        "temp_rec_name": "当前录音",
        "status_done": "完成",
        "status_deleted": "已删除",
        "btn_delete": "删除",
        "warn_save": "请先保存！",
        "player_title": "播放器",
        "play_volume": "音量",
        "btn_save": "保存",
        "list_date": "日期",
        "list_name": "文件名",
        "list_current": "🔴 当前",
        "library_title": "最近的录音",
        "btn_choose_folder": "选择文件夹",
        "btn_open_explorer": "资源管理器",
        "tray_open": "打开",
        "tray_exit": "退出",
        "autostart": "随 Windows 启动",
        "status_save_success": "文件已保存",
        "status_save_error": "保存失败",
        "btn_cancel": "取消",
        "unit_sec": "秒",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "版本 0.6 Beta，可能包含错误",
        "about_description": (
            "完全掌控您的声音。JB Audio Recorder 是一款专为追求音质的用户打造的轻量级强大工具。"
            "无需复杂设置：选择比特率和频率，即可录制流行格式的音频。"
            "内置智能降噪算法可有效清除背景噪音，还原清晰人声。\n\n"
            "便捷的播放器与媒体库。无需再费力在系统中查找文件。直接在应用内试听录音，"
            "决定是保存还是重录。所有成功的录音都会自动归档至可视化媒体库，"
            "按日期整理，一键即可查找和打开。\n\n"
            "随心所欲的工作方式。录音机完美融入您的工作流程：支持后台运行或始终“置顶显示”。"
            "通过快捷键控制录音，无需担心结果——系统会在退出时提醒您保存未保存的文件。"
        ),
        "about_links": "GitHub：",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "日本語 (Japanese)": {
        "reset_settings": "デフォルト設定にリセット",
        "reset_settings_confirm": "すべての設定をデフォルト値にリセットしてもよろしいですか？",
        "reset_settings_success": "設定が正常にリセットされました！",
        "device_setting_label": "録音デバイス",
        "device_help": "「動いているなら触るな」とよく言われます",
        "exit_unsaved_warning": "現在録音中であるか、音声が保存されていません。\n本当に終了しますか？",
        "save_path_label": "録音保存フォルダ",
        "tray_settings": "設定",
        "lang_help": "中国語も話せます！",
        "choose_file": "ファイルを選択",
        "work_background_help": "アプリが最小化されている間も録音と再生が可能",
        "autostart_help": "いつでもすぐに使えるように",
        "auto_save_help": "プレーヤーでのプレビューなしで、録音を直接ディスクに保存",
        "always_on_top_help": "アプリが他のすべてのウィンドウの最前面に固定されます",
        "hotkeys_label": "ホットキー",
        "hotkeys_help": "[Ctrl+スペース] 録音/停止, [Ctrl+Shift+スペース] 一時停止, [Ctrl+Shift+S] 保存",
        "exit_title": "終了",
        "exit_confirm": "本当に終了しますか？",
        "dont_ask": "次回から表示しない",
        "exit_btn": "終了",
        "cancel_btn": "キャンセル",
        "always_on_top": "常に最前面",
        "auto_save": "自動保存",
        "nav_rec": "録音",
        "nav_set": "設定",
        "nav_settings": "パラメータ",
        "nav_about": "情報",
        "status_ready": "準備完了",
        "status_recording": "録音中...",
        "status_paused": "一時停止",
        "btn_record": "録音",
        "btn_stop": "停止",
        "btn_pause": "一時停止",
        "btn_resume": "再開",
        "input_volume": "音量",
        "device": "デバイス",
        "format": "形式",
        "noise": "ノイズ除去",
        "now_playing": "再生中",
        "no_file": "ファイルなし",
        "tab_settings": "アプリ設定",
        "work_background": "バックグラウンド",
        "language_label": "言語 (Language)",
        "folder_label": "フォルダ",
        "bitrate": "ビットレート",
        "frequency": "周波数",
        "mode": "モード",
        "temp_rec_name": "現在の録音",
        "status_done": "完了",
        "status_deleted": "削除済み",
        "btn_delete": "削除",
        "warn_save": "先に保存してください！",
        "player_title": "プレイヤー",
        "play_volume": "音量",
        "btn_save": "保存",
        "list_date": "日付",
        "list_name": "ファイル名",
        "list_current": "🔴 現在",
        "library_title": "最近の録音",
        "btn_choose_folder": "フォルダ選択",
        "btn_open_explorer": "エクスプローラー",
        "tray_open": "開く",
        "tray_exit": "終了",
        "autostart": "Windows起動時に実行",
        "status_save_success": "ファイルを保存しました",
        "status_save_error": "保存エラー",
        "btn_cancel": "キャンセル",
        "unit_sec": "秒",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "バージョン 0.6 ベータ、バグの可能性あり",
        "about_description": (
            "あなたのサウンドを完全にコントロール。JB Audio Recorderは、品質を重視する方向けの軽量かつパワフルなツールです。"
            "複雑な設定は不要です。ビットレートと周波数を選択して、一般的なフォーマットで録音できます。"
            "内蔵のインテリジェントノイズ除去アルゴリズムが、バックグラウンドノイズからあなたの声をクリアにします。\n\n"
            "便利なプレーヤーとライブラリ。システム全体からファイルを探す必要はもうありません。アプリ内で録音を"
            "すぐに再生し、保存するか上書きするかを決定できます。成功した録音はすべて視覚的なライブラリに保存され、"
            "日付順に整理され、ワンクリックで簡単に見つけて開くことができます。\n\n"
            "好きなように作業できます。レコーダーはあなたのワークフローに完璧にフィットします。バックグラウンドで動作させることも、「常に最前面」に置くことも可能です。"
            "ホットキーで録音を制御し、結果について心配する必要はありません。システムは終了時に保存されていないファイルについて警告します。"
        ),
        "about_links": "GitHub：",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    },
    "한국어 (Korean)": {
        "reset_settings": "기본 설정으로 재설정",
        "reset_settings_confirm": "모든 설정을 기본값으로 재설정하시겠습니까?",
        "reset_settings_success": "설정이 성공적으로 재설정되었습니다!",
        "device_setting_label": "녹음 장치",
        "device_help": "흔히 말하죠: \"작동한다면 건드리지 마세요\"",
        "exit_unsaved_warning": "녹음 중이거나 저장되지 않은 오디오가 있습니다.\n정말 종료하시겠습니까?",
        "save_path_label": "녹음 저장 폴더",
        "tray_settings": "설정",
        "lang_help": "중국어도 할 수 있어요!",
        "choose_file": "파일 선택",
        "work_background_help": "앱이 최소화되어 있을 때도 녹음 및 재생 가능",
        "autostart_help": "언제나 바로 사용할 수 있도록",
        "auto_save_help": "플레이어에서 미리 듣지 않고 녹음을 바로 디스크에 저장",
        "always_on_top_help": "앱이 다른 모든 창 위에 항상 표시됩니다",
        "hotkeys_label": "단축키",
        "hotkeys_help": "[Ctrl+스페이스] 시작/중지, [Ctrl+Shift+스페이스] 일시 중지, [Ctrl+Shift+S] 저장",
        "exit_title": "종료",
        "exit_confirm": "정말 종료하시겠습니까?",
        "dont_ask": "다시 묻지 않음",
        "exit_btn": "종료",
        "cancel_btn": "취소",
        "always_on_top": "항상 맨 위에",
        "auto_save": "자동 저장",
        "nav_rec": "녹음기",
        "nav_set": "설정",
        "nav_settings": "녹음 매개변수",
        "nav_about": "정보",
        "status_ready": "준비 완료",
        "status_recording": "녹음 중...",
        "status_paused": "일시 중지",
        "btn_record": "녹음",
        "btn_stop": "중지",
        "btn_pause": "일시 중지",
        "btn_resume": "재개",
        "input_volume": "입력 볼륨",
        "device": "장치",
        "format": "형식",
        "noise": "노이즈 감소",
        "now_playing": "재생 중",
        "no_file": "파일 없음",
        "tab_settings": "앱 설정",
        "work_background": "백그라운드",
        "language_label": "언어 (Language)",
        "folder_label": "폴더",
        "bitrate": "비트레이트",
        "frequency": "주파수",
        "mode": "녹음 모드",
        "temp_rec_name": "현재 녹음",
        "status_done": "녹음 완료",
        "status_deleted": "삭제됨",
        "btn_delete": "삭제",
        "warn_save": "먼저 저장하세요!",
        "player_title": "플레이어",
        "play_volume": "볼륨",
        "btn_save": "저장",
        "list_date": "날짜",
        "list_name": "파일 이름",
        "list_current": "🔴 현재 녹음",
        "library_title": "최근 녹음",
        "btn_choose_folder": "폴더 선택",
        "btn_open_explorer": "탐색기",
        "tray_open": "열기",
        "tray_exit": "종료",
        "autostart": "Windows와 함께 시작",
        "status_save_success": "파일이 저장되었습니다",
        "status_save_error": "저장 오류",
        "btn_cancel": "취소",
        "unit_sec": "초",
        "tray_tip": "JB Audio Recorder",
        "about_app_title": "JB AUDIO RECORDER",
        "about_version": "버전 0.6 베타, 버그 가능성 있음",
        "about_description": (
            "완벽한 사운드 제어. JB Audio Recorder는 품질을 중시하는 사용자를 위한 가볍고 강력한 도구입니다. "
            "복잡한 설정은 잊으세요: 비트레이트와 주파수를 선택하여 인기 있는 형식으로 오디오를 녹음하세요. "
            "내장된 지능형 노이즈 감소 알고리즘이 배경 소음으로부터 목소리를 깨끗하게 정리해줍니다.\n\n"
            "편리한 플레이어 및 라이브러리. 더 이상 시스템 전체에서 파일을 찾을 필요가 없습니다. 앱에서 바로 녹음을 들어보고 "
            "저장할지 덮어쓸지 결정하세요. 모든 성공적인 녹음은 시각적 라이브러리로 이동하며, "
            "날짜별로 쉽게 찾아 클릭 한 번으로 열 수 있습니다.\n\n"
            "원하는 대로 작업하세요. 레코더는 작업 흐름에 완벽하게 맞습니다: 백그라운드에서 실행되거나 '항상 맨 위'에 있을 수 있습니다. "
            "단축키로 녹음을 제어하고 결과에 대해 걱정하지 마세요 — 시스템은 종료 시 저장되지 않은 파일에 대해 경고합니다."
        ),
        "about_links": "GitHub:",
        "about_github_status": "jeffbennington/JB-Audio-Recorder",
        "about_author": "Jeff Bennington",
        "about_signature": "From Russia with Love"
    }
}